from app.schemas.intent_customers import IntentCustomerCreate, IntentCustomerUpdate, IntentCustomerResponse, CustomerJudgeRequest
from app.schemas.daily_reports import DailyReportCreate, DailyReportResponse, DailyReportSummary
from app.schemas.leave_applications import LeaveApplicationCreate, LeaveApplicationUpdate, LeaveApplicationResponse
from app.schemas.feedback_tickets import FeedbackTicketCreate, FeedbackTicketUpdate, FeedbackTicketResponse
from app.schemas.activities import ActivityCreate, ActivityUpdate, ActivityResponse, ActivityRegisterRequest