from sqlalchemy import Column, Integer, String, Text, Date, Float, Boolean, DateTime
from sqlalchemy.sql import func
from app.core.database import Base

class IntentCustomer(Base):
    __tablename__ = "customer_info"
    
    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    customer_id = Column(String(50), nullable=False)
    name = Column(String(50), nullable=False)
    gender = Column(String(20), nullable=False)
    age = Column(Integer, nullable=False)
    province = Column(String(100), nullable=False)
    city = Column(String(100), nullable=False)
    phone_number = Column(String(100), nullable=False)
    channel_type = Column(String(50), nullable=False)
    channel_name = Column(String(100), nullable=False)
    source_URL = Column(String(100))
    education_level = Column(String(50), nullable=False)
    education_status = Column(String(50), nullable=False)
    school_name = Column(String(100), nullable=False)
    major = Column(String(100), nullable=False)
    graduate_time = Column(Date, nullable=False)
    english_score = Column(String(50))
    german_level = Column(String(20))
    education_verified = Column(Boolean)
    target_country = Column(String(50), nullable=False)
    target_project_type = Column(String(100), nullable=False)
    target_major = Column(String(100), nullable=False)
    target_degree = Column(String(50), nullable=False)
    study_purpose = Column(String(100))
    family_income_level = Column(String(50))
    budget_range = Column(String(50))
    loan_acceptance = Column(Boolean)
    payment_ability_level = Column(Boolean)
    accept_overseas_study = Column(Boolean)
    accept_closed_training = Column(Boolean)
    accept_enterprise_training = Column(Boolean)
    learning_ability_score = Column(Integer)
    education_upgrade_intention = Column(Boolean)
    career_upgrade_intention = Column(Boolean)
    employment_demand = Column(Boolean)
    immigration_intention = Column(Boolean)
    overseas_development = Column(Boolean)
    high_salary_expectation = Column(Boolean)
    stable_job_expectation = Column(Boolean)
    passport_available = Column(Boolean)
    exit_restriction_risk = Column(Boolean)
    credit_risk = Column(Boolean)
    visa_refusal_history = Column(Boolean)
    high_risk_flag = Column(Boolean)
    consult_phase = Column(String(50))
    follow_status = Column(String(50), nullable=False)
    assigned_consultant = Column(String(50), nullable=False)
    last_follow_time = Column(DateTime, nullable=False)
    follow_notes = Column(Text, nullable=False)
    create_time = Column(DateTime(timezone=True), server_default=func.now())
    update_time = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())